### ISSUE TITLE
Not activating MSS310AU switch

### ISSUE THREAD

**Issue by troykelly** [carlosatta/hassio-addons#20]
Sensors for a MSS310AU are working, but activating the switch seems to fail.

There is an error at startup:
`[WARN][Switch][Exhaust Matty Troy Bathroom] Impossibile retrieve real status: Cannot read property 'togglex' of undefined.
`

Switching seems to generate this error:
```
Error: Timeout
    at Timeout.waitingMessageIds.(anonymous function).timeout.setTimeout [as _onTimeout] (/usr/src/hassio_meross/node_modules/meross-cloud/index.js:292:64)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: Timeout
    at Timeout.waitingMessageIds.(anonymous function).timeout.setTimeout [as _onTimeout] (/usr/src/hassio_meross/node_modules/meross-cloud/index.js:292:64)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: Timeout
    at Timeout.waitingMessageIds.(anonymous function).timeout.setTimeout [as _onTimeout] (/usr/src/hassio_meross/node_modules/meross-cloud/index.js:292:64)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Error: Timeout
    at Timeout.waitingMessageIds.(anonymous function).timeout.setTimeout [as _onTimeout] (/usr/src/hassio_meross/node_modules/meross-cloud/index.js:292:64)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Let me know what information you need.

**Comment by troykelly** [comment]
bootstrap() `info.all`:
```json
bootstrap: Switch {
  "system": {
    "hardware": {
      "type": "mss310",
      "subType": "us",
      "version": "1.0.0",
      "chipType": "MT7688",
      "uuid": "00000000000000000000000000000000",
      "macAddress": "00:00:00:00:00:00"
    },
    "firmware": {
      "version": "1.1.18",
      "compileTime": "2018-12-03 11:15:36",
      "wifiMac": "00:00:00:00:00:00",
      "innerIp": "999.999.999.999",
      "server": "iot.meross.com",
      "port": 2001,
      "secondServer": "smart.meross.com",
      "secondPort": 2001,
      "userId": 237110
    },
    "time": {
      "timestamp": 1560166819,
      "timezone": "Australia/Sydney",
      "timeRule": [
        [
          1554566400,
          36000,
          0
        ],
        [
          1570291200,
          39600,
          1
        ],
        [
          1586016000,
          36000,
          0
        ],
        [
          1601740800,
          39600,
          1
        ],
        [
          1617465600,
          36000,
          0
        ],
        [
          1633190400,
          39600,
          1
        ],
        [
          1648915200,
          36000,
          0
        ],
        [
          1664640000,
          39600,
          1
        ],
        [
          1680364800,
          36000,
          0
        ],
        [
          1696089600,
          39600,
          1
        ],
        [
          1712419200,
          36000,
          0
        ],
        [
          1728144000,
          39600,
          1
        ],
        [
          1743868800,
          36000,
          0
        ],
        [
          1759593600,
          39600,
          1
        ],
        [
          1775318400,
          36000,
          0
        ],
        [
          1791043200,
          39600,
          1
        ],
        [
          1806768000,
          36000,
          0
        ],
        [
          1822492800,
          39600,
          1
        ],
        [
          1838217600,
          36000,
          0
        ],
        [
          1853942400,
          39600,
          1
        ]
      ]
    },
    "online": {
      "status": 1
    }
  },
  "control": {
    "toggle": {
      "onoff": 0,
      "lmTime": 1560165309
    },
    "trigger": [],
    "timer": []
  }
}
```
